### ISSUE TITLE
Move static constexpr variables to public in hand-modes.cpp

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-control-systems-2022#107]
static constexpr int min_angle_ = 30;
        static constexpr int neutral_angle_ = 90;
        static constexpr int max_angle_ = 180;
should be public at the top of the class.

**Comment by naterpotatoers** [comment]
@Mchan2003 is this still in the works?

**Comment by Coreyboy1820** [comment]
No longer needed.
