### ISSUE TITLE
Research GPS modules 

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-control-systems-2022#110]
Need a GPS that talks over UART 
Will need a GPS for competition purposes. Dev2 doesn't have any GPS drivers so we would need to create our own driver.

**Comment by acarrou** [comment]
The [GPS over UART](https://www.amazon.com/VK-162-G-Mouse-External-Navigation-Raspberry/dp/B01EROIUEW/ref=sr_1_3?keywords=usb+gps+receiver&qid=1658897009&sr=8-3) I found
