### ISSUE TITLE
fix drives JSON body parser format

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-control-systems-2022#112]
Right now it is

       "\r\n\r\n{\n"
        "  \"heartbeat_count\": %d,\n"
        "  \"is_operational\": %d,\n"
        "  \"wheel_shift\": %d,\n"
        "  \"drive_mode\": \"%c\",\n"
        "  \"speed\": %d,\n"
        "  \"angle\": %d\n"
        "}";

when it should be:

    "{\"heartbeat_count\":%d,\"is_operational\":%d,\"wheel_shift\":%d,\"drive_mode\":\"%c\",\"speed\":%d,\"angle\":%d}"

**Comment by Coreyboy1820** [comment]
Fixed.
