### ISSUE TITLE
Fix drive serial command bug at max angle & speed

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-control-systems-2022#136]
When Adrien flashes using his laptop his mcu bugs out when driving rover at max speed and attempting to turn. It looks like the speed slows down as if speed was set to zero momentarily. Not sure why that's happening. When Xander or Nate flash the same code using T440p laptops it works fine.

**Comment by Coreyboy1820** [comment]
This seems to only be the case for the legions, will do further testing but closing this issue for now.
