### ISSUE TITLE
Demo for arm mimic

### ISSUE THREAD

**Issue by Coreyboy1820** [SJSURoboticsTeam/urc-control-systems-2022#175]
We want a simple demo setup for the arm mimic which will simulate what we will be doing. This involves hardware, we want to be able to move the potentiometers and get values.

**Comment by PhazonicRidley** [comment]
Hello, I would like to take this on. I have already started talking to the mimic team a bit on discord. We've decided to use an ardiuno.

**Comment by PhazonicRidley** [comment]
Completed
