### ISSUE TITLE
Fix the context bug in subsystem-drive main

### ISSUE THREAD

**Issue by starphys** [SJSURoboticsTeam/urc-control-systems-2022#181]
This shouldn't be like this:

https://github.com/SJSURoboticsTeam/urc-control-systems-2022/blob/main/subsystem-drive/source/main.cpp#L84

**Comment by starphys** [comment]
Just need to move lines 83 through 85, probably an error from a merge

**Comment by Coreyboy1820** [comment]
This has been done.
