### ISSUE TITLE
Make rr9 handler

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-control-systems-2022#182]
The rr9 will only require a singular angle from the dto. 
The rr9 will be moved when mode value is set to 'R' and will use the first value from the angles array as shown below
{ "heartbeat_count": 0, ”is_operational": 1, "mode": "R", "angles": [1, 2, 3, 4, 5] }

**Comment by Coreyboy1820** [comment]
This has been finished.
