### ISSUE TITLE
Research low latency WiFi communication for Rover Drive

### ISSUE THREAD

**Issue by acarrou** [SJSURoboticsTeam/urc-control-systems-2022#191]
We currently use a phone as a hotspot to communicate from the webserver to the rover RPI. Some latency occurs from the hotspot, so we should try looking for other solutions, such as testing the school network or finding a good wifi AP to bridge the webserver and pi.

**Comment by kammce** [comment]
You can use a WiFi AP for this.

**Comment by Coreyboy1820** [comment]
Khalil gave us a solution.

> You can use a WiFi AP for this.
