### ISSUE TITLE
fix compilation errors in hand draft branch

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-control-systems-2022#62]
Theres a ton of new stuff that is broken and needs to be fixed to pass unit tests. please get it compiling so we can merge it in.

**Comment by kammce** [comment]
Can this be broken up so that the scope of the problem can be better illustrated? Is this something small that deserves to be in a single issue? Sounds like there are a lot of problems by the description of "ton".
