### ISSUE TITLE
Implement motor class to remove tight coupling with RMD driver

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-control-systems-2022#77]
By having a motor class/interface we can remove that tight coupling from rmd driver which makes it easier to change motor drivers in the future. Just a good best practice to implement here.

**Comment by Coreyboy1820** [comment]
@naterpotatoers I don't think we can implement this since RMD is in dev2 and rmd would have to inherit the interface right?

**Comment by Coreyboy1820** [comment]
Implemented a RMDencoder class to satisfy this.
