### ISSUE TITLE
Devise a better mission control data format

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-control-systems-2022#80]
JSON is not ideal, maybe prefer something more basic like a simple comma delimited format? E.g `1,A90,S100,D0`

**Comment by naterpotatoers** [comment]
@Coreyboy1820 Might be a good issue to work on as a team next weekend

**Comment by Coreyboy1820** [comment]
This should be on the backburner for now, could be a good side task.

**Comment by Coreyboy1820** [comment]
This is no longer needed.
