### ISSUE TITLE
RulesEngine Class Name Clash in Subsystem-Arm

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-control-systems-2022#87]
Have two classes in Subsystem Arm called RulesEngine. One is for hand, the other is for arm. We should consider ways to prevent the clashing of the two by either

1. Creating separate namespaces
2. Rename the classes e.g. JointRulesEngine & HandRulesEngine
3. Combine the two classes together and have one singlular RuleEngine class. 

I think I personally like the later tbh...

**Comment by 50xp50** [comment]
> Have two classes in Subsystem Arm called RulesEngine. One is for hand, the other is for arm. We should consider ways to prevent the clashing of the two by either
> 
> 1. Creating separate namespaces
> 2. Rename the classes e.g. JointRulesEngine & HandRulesEngine
> 3. Combine the two classes together and have one singlular RuleEngine class.
> 
> I think I personally like the later tbh...

We are going to use option 2 per corey's decision, the renaming may potentially break some things temporarily until fixed
